### ISSUE TITLE
modules missing

### ISSUE THREAD

**Issue by ammaranasim90** [hin1115/SuperpixelGCN-Segmentation#4]
Greetings
Are the folders pytorch_ssn and ssn-pytorch are supposed to be empty ,if not can you share the relevant files

**Comment by HoinJung** [comment]
I guess the connections to submodule are missing.  Here are the git links of the superpixel sampling networks. You can clone them directly into the folder.
https://github.com/CYang0515/pytorch_ssn.git
https://github.com/perrying/ssn-pytorch.git
